esphome:
  name: air-quality
  platform: ESP8266
  board: d1_mini_lite

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none # constantly plugged in no need for wifi power saving
  manual_ip:
    static_ip: 192.168.1.26
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100

uart:
  rx_pin: D4
  tx_pin: D5 # this pin is actualy not used since we do not transmit anything to the sensor
  baud_rate: 9600

i2c:
  scl: D1
  sda: D2
  id: bus_a

sensor:
  - platform: pm1006
    pm_2_5:
      name: "pm2.5"

  - platform: aht10
    temperature:
      name: "Temperature"
      id: living_room_temperature
    humidity:
      name: "Humidity"
      id: living_room_humidity