{
 "title": "Weather Station",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  InsideTemp\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    },
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  OutsideTemp\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  InsideHumidity\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    },
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  OutsideHumidity\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Pression & Humidex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Pressure AS \"Pressure\"\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    },
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Humidex\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  InsideTemp\nFROM Stats\nORDER BY Date"
    },
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  OutsideTemp\nFROM Stats\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  OutsideHumidity\nFROM Stats\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Pression",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Humidex",
   "type": "gauge",
   "description": "https://www.researchgate.net/profile/Milica_Lukic2/publication/335293174/figure/tbl1/AS:794290485735430@1566385017643/The-scale-of-Humidex-and-the-degree-of-comfort.png",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Humidex\nFROM Stats\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  { "title": "Server Time (UTC)", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 } },
  { "title": "France Time (UTC+1)", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 } },
  {
   "title": "last values",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}