esphome:
  name: outside
  platform: ESP32
  board: esp32doit-devkit-v1

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  manual_ip:
    static_ip: 192.168.1.28
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100

dallas:
  - pin: GPIO23

sensor:
  - platform: dallas
    address: 0x010301a279737028
    name: "Outside Temperature"
  - platform: adc
    pin: 34
    name: "Battery Level"
    update_interval: 60s
    filters:
      - multiply: 100
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 1 -> 4.2
  - platform: adc
    pin: 32
    name: "Solar Level"
    update_interval: 60s
    filters:
      - multiply: 100
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 1 -> 4.2