esphome:
  name: outside
  platform: ESP8266
  board: d1_mini_lite

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  manual_ip:
    static_ip: 192.168.1.28
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100

uart:
  rx_pin: D2
  tx_pin: D4
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "pm2.5"
