esphome:
  name: temp-sens-screen
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  manual_ip:
    static_ip: 192.168.1.29
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100

# font:
  # - file: "gfonts://Roboto Mono"
  #   id: roboto
  #   size: 18

i2c:
  id: bus_a
  sda: D2
  scl: D1
  scan: true

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      id: bme280_temperature
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     reset_pin: D0
#     address: 0x3C
#     lambda: |-
#       //it.fill(COLOR_ON);
#       it.printf(0, 0, id(roboto), "%.1f °C", id(bme280_temperature).state);
#       it.printf(0, 22, id(roboto), "%.1f hPa", id(bme280_pressure).state);
#       it.printf(0, 44, id(roboto), "%.1f p", id(bme280_humidity).state);
#       // If the sensor has the value 30.02, the result will be: "The sensor value is: 30.0"
