esphome:
  name: temp-sens-screen
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  manual_ip:
    static_ip: 192.168.1.29
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100

i2c:
  - id: bus_a
    sda: D1
    scl: D2
    scan: true

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 60s


display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.line(0, 0, 50, 50);